-- [SOURCE] source_schema_change_v4.sql
-- Strictly aligned with MySQL dump column orders and counts.
-- Using TIMESTAMP NULL for dates and TEXT for potentially long strings.

SET search_path TO source;

-- 1. MST_ROLE
CREATE TABLE IF NOT EXISTS source.mst_role (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    code VARCHAR(100),
    iflg INTEGER,
    created_by INTEGER,
    created_on TIMESTAMP NULL,
    modified_on TIMESTAMP NULL,
    modified_by INTEGER,
    is_deleted INTEGER
);

-- 2. MST_REGION
CREATE TABLE IF NOT EXISTS source.mst_region (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    code VARCHAR(100),
    iflg INTEGER,
    created_by INTEGER,
    created_on TIMESTAMP NULL,
    modified_on TIMESTAMP NULL,
    modified_by INTEGER,
    is_deleted INTEGER,
    rank_region INTEGER
);

-- 3. MST_AREA
CREATE TABLE IF NOT EXISTS source.mst_area (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    code VARCHAR(100),
    iflg INTEGER,
    region_id INTEGER,
    created_by INTEGER,
    created_on TIMESTAMP NULL,
    modified_on TIMESTAMP NULL,
    modified_by INTEGER,
    is_deleted INTEGER
);

-- 4. MST_DONOR
CREATE TABLE IF NOT EXISTS source.mst_donor (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    code VARCHAR(100),
    iflg INTEGER,
    created_by INTEGER,
    created_on TIMESTAMP NULL,
    modified_on TIMESTAMP NULL,
    modified_by INTEGER,
    is_deleted INTEGER
);

-- 5. MST_SCHOOL_TYPE
CREATE TABLE IF NOT EXISTS source.mst_school_type (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(100),
    name VARCHAR(255),
    display_order INTEGER
);

-- 6. MST_SCHOOL
CREATE TABLE IF NOT EXISTS source.mst_school (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    code VARCHAR(100),
    udise_code VARCHAR(100),
    udise_name VARCHAR(255),
    iflg INTEGER,
    contact_name VARCHAR(255),
    address TEXT,
    pincode VARCHAR(50),
    phone_1 VARCHAR(50),
    phone_2 VARCHAR(50),
    phone_3 VARCHAR(50),
    email_1 VARCHAR(255),
    email_2 VARCHAR(255),
    latitude VARCHAR(100),
    area_id INTEGER,
    state_management INTEGER,
    national_management INTEGER,
    school_category INTEGER,
    school_type INTEGER,
    location INTEGER,
    created_by INTEGER,
    created_on TIMESTAMP NULL,
    modified_on TIMESTAMP NULL,
    modified_by INTEGER,
    is_deleted INTEGER,
    longitude VARCHAR(100)
);

-- 7. MST_USER
CREATE TABLE IF NOT EXISTS source.mst_user (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    code VARCHAR(100),
    iflg INTEGER,
    role_id INTEGER,
    report_id INTEGER,
    contact_number VARCHAR(100),
    address TEXT,
    pass VARCHAR(255),
    email VARCHAR(255),
    region_id INTEGER,
    area_id INTEGER,
    created_by INTEGER,
    created_on TIMESTAMP NULL,
    modified_on TIMESTAMP NULL,
    modified_by INTEGER,
    is_deleted INTEGER,
    base_program_id INTEGER,
    donor_id INTEGER,
    circle_id INTEGER,
    has_b_ed_degree VARCHAR(50),
    has_d_ed_degree VARCHAR(50),
    joining_date DATE,
    pg_degree VARCHAR(255),
    ug_degree VARCHAR(255)
);

-- 8. MST_ACTIVITY_TYPE
CREATE TABLE IF NOT EXISTS source.mst_activity_type (
    id INTEGER PRIMARY KEY,
    code VARCHAR(255),
    name VARCHAR(255),
    additional_info TEXT,
    iflg INTEGER,
    created_by INTEGER,
    created_on TIMESTAMP NULL,
    modified_on TIMESTAMP NULL,
    modified_by INTEGER,
    is_deleted INTEGER,
    is_adhoc INTEGER
);

-- 9. TXN_PROGRAM
CREATE TABLE IF NOT EXISTS source.txn_program (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    donor_id INTEGER,
    area_id INTEGER,
    program_type_id INTEGER,
    start_date DATE,
    end_date DATE,
    name VARCHAR(255),
    created_by INTEGER,
    created_on TIMESTAMP NULL,
    modified_on TIMESTAMP NULL,
    modified_by INTEGER,
    is_deleted INTEGER,
    donor_exposure_target INTEGER,
    operational_exposure_target INTEGER,
    total_workdays_target INTEGER,
    school_session_days_target INTEGER,
    school_session_exposure_target INTEGER,
    community_visit_days_target INTEGER,
    community_visit_exposure_target INTEGER,
    sciece_fair_days_target INTEGER,
    science_fair_exposure_target INTEGER,
    ttp_days_target INTEGER,
    ttp_exposure_target INTEGER,
    sp_days_target INTEGER,
    sp_exposure_target INTEGER,
    ov_days_target INTEGER,
    ov_exposure_target INTEGER,
    yil_days_target INTEGER,
    yil_exposure_target INTEGER,
    instructor_capacity INTEGER,
    location VARCHAR(255),
    periodicity_id INTEGER
);

-- 10. CONF_PROGRAM_SCHOOL_MAPPING
CREATE TABLE IF NOT EXISTS source.conf_program_school_mapping (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    school_id INTEGER,
    program_id INTEGER,
    date DATE,
    activity_flg INTEGER,
    activity_type_id INTEGER,
    created_by INTEGER,
    created_on TIMESTAMP NULL,
    modified_on TIMESTAMP NULL,
    modified_by INTEGER,
    is_deleted INTEGER
);

-- 11. TXN_SESSION
CREATE TABLE IF NOT EXISTS source.txn_session (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    instructor_id INTEGER,
    program_school_mapped_id INTEGER,
    shift_id INTEGER,
    date DATE,
    additional_info TEXT,
    created_by INTEGER,
    created_on TIMESTAMP NULL,
    modified_on TIMESTAMP NULL,
    modified_by INTEGER,
    is_deleted INTEGER,
    is_overdue INTEGER DEFAULT 0
);

-- 12. MST_SUBJECT
CREATE TABLE IF NOT EXISTS source.mst_subject (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    code VARCHAR(100),
    iflg INTEGER,
    description TEXT,
    created_by INTEGER,
    created_on TIMESTAMP NULL,
    modified_on TIMESTAMP NULL,
    modified_by INTEGER,
    is_deleted INTEGER
);

-- 13. MST_TOPIC
CREATE TABLE IF NOT EXISTS source.mst_topic (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    iflg INTEGER,
    description TEXT,
    subject_id INTEGER,
    created_by INTEGER,
    created_on TIMESTAMP NULL,
    modified_on TIMESTAMP NULL,
    modified_by INTEGER,
    is_deleted INTEGER
);

-- 14. TXN_FEEDBACK_EXPOSURE
CREATE TABLE IF NOT EXISTS source.txn_feedback_exposure (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    session_id INTEGER,
    class_id INTEGER,
    section VARCHAR(100),
    boys INTEGER,
    girls INTEGER,
    created_by INTEGER,
    created_on TIMESTAMP NULL,
    modified_on TIMESTAMP NULL,
    modified_by INTEGER,
    is_deleted INTEGER
);

-- 15. RPT_FEEDBACK
CREATE TABLE IF NOT EXISTS source.rpt_feedback (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    session_id INTEGER,
    subject_id INTEGER,
    subject_name VARCHAR(255),
    topic_id INTEGER,
    topic_name VARCHAR(255),
    demo_session INTEGER,
    hands_on_session INTEGER,
    no_of_guest__others INTEGER,
    session_duration DECIMAL(10,2),
    no_of_teachers INTEGER,
    concept_id INTEGER,
    concept_name VARCHAR(255),
    location INTEGER,
    no_of_girls INTEGER,
    no_of_boys INTEGER,
    no_of_participating_school INTEGER,
    school_id INTEGER,
    school_name VARCHAR(255),
    no_of_young_instructor INTEGER,
    no_of_model_displayed INTEGER,
    details TEXT,
    no_of_teacher_visited INTEGER,
    no_of_school_visited INTEGER,
    village VARCHAR(255),
    location_name VARCHAR(255),
    no_of_men INTEGER,
    no_of_women INTEGER,
    mode_of_engagement INTEGER
);

-- 16. MST_SHIFT
CREATE TABLE IF NOT EXISTS source.mst_shift (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    code VARCHAR(100),
    additional_info TEXT,
    iflg INTEGER,
    created_by INTEGER,
    created_on TIMESTAMP NULL,
    modified_on TIMESTAMP NULL,
    modified_by INTEGER,
    is_deleted INTEGER
);

-- 17. TXN_VEHICLE_LOG
CREATE TABLE IF NOT EXISTS source.txn_vehicle_log (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    vehicle_id INTEGER,
    driver_id INTEGER,
    program_id INTEGER,
    instructor_id INTEGER,
    date DATE,
    vehicle_used_flag INTEGER,
    vehicle_not_used_reason TEXT,
    open_reading INTEGER,
    closed_reading INTEGER,
    fuel_price FLOAT,
    fuel_quantity FLOAT,
    created_by INTEGER,
    created_on TIMESTAMP NULL,
    modified_on TIMESTAMP NULL,
    modified_by INTEGER,
    is_deleted INTEGER
);

-- 18. MST_CLASS
CREATE TABLE IF NOT EXISTS source.mst_class (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    grade_id INTEGER,
    section_id INTEGER,
    medium_id INTEGER,
    type_id INTEGER,
    code VARCHAR(100),
    iflg INTEGER,
    school_id INTEGER,
    boys INTEGER,
    girls INTEGER,
    created_by INTEGER,
    created_on TIMESTAMP NULL,
    modified_on TIMESTAMP NULL,
    modified_by INTEGER,
    is_deleted INTEGER
);

-- 19. MST_ADHOC_SESSION_FEEDBACK_ANSWERS
CREATE TABLE IF NOT EXISTS source.mst_adhoc_session_feedback_answers (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    instructor_id INTEGER,
    program_id INTEGER,
    activity_type_id INTEGER,
    answer_obj TEXT,
    date DATE,
    exposures INTEGER,
    is_overdue INTEGER DEFAULT 0
);

-- 20. CONF_SCHOOL_SCHOOL_TYPE_MAPPING
CREATE TABLE IF NOT EXISTS source.conf_school_school_type_mapping (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    school_id INTEGER,
    school_type_id INTEGER
);

-- 21. MST_CLASS_2025_2026
CREATE TABLE IF NOT EXISTS source.mst_class_2025_2026 (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    grade_id INTEGER,
    section_id INTEGER,
    medium_id INTEGER,
    type_id INTEGER,
    code VARCHAR(100),
    iflg INTEGER,
    school_id INTEGER,
    boys INTEGER,
    girls INTEGER,
    created_by INTEGER,
    created_on TIMESTAMP NULL,
    modified_on TIMESTAMP NULL,
    modified_by INTEGER,
    is_deleted INTEGER
);

-- 22. TXN_FEEDBACK_ANSWER
CREATE TABLE IF NOT EXISTS source.txn_feedback_answer (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    session_id INTEGER,
    answer_obj TEXT,
    created_by INTEGER,
    created_on TIMESTAMP NULL,
    modified_on TIMESTAMP NULL,
    modified_by INTEGER,
    is_deleted INTEGER,
    is_overdue INTEGER DEFAULT 0
);

-- 23. MST_VEHICLE
CREATE TABLE IF NOT EXISTS source.mst_vehicle (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    vehicle_name VARCHAR(255),
    vehicle_number VARCHAR(100),
    created_by INTEGER,
    created_on TIMESTAMP NULL,
    modified_on TIMESTAMP NULL,
    modified_by INTEGER,
    is_deleted INTEGER,
    program_id INTEGER,
    area_id INTEGER
);
